name: isabelsilverman-fitnesseffect-latest
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.7
  - r-base=4.0
  - pandas=1.0
  - numpy=1.18
  - matplotlib=3.2
  - seaborn=0.10
